# -*- coding: utf-8 -*-
import functools
from agentscope.message import TextBlock
from agentscope.tool import ToolResponse


def sandbox_tool_adapter(func):
    """
    Sandbox Tool Adapter.

    Wraps a sandbox tool function so that its output is always converted
    into a ToolResponse object, which is required by the Toolkit.

    This adapter preserves the original function signature and docstring
    so that JSON schemas can be correctly generated by the Toolkit.

    Args:
        func: Original sandbox tool function (may return dict, string, etc.).

    Returns:
        A callable that produces ToolResponse instead of raw data.
    """

    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        res = func(*args, **kwargs)
        if isinstance(res, ToolResponse):
            return res
        # TODO: fix this
        return ToolResponse(content=[TextBlock(type="text", text=str(res))])

    return wrapper
